/**
 * Serves the pre-cropped building image from output/crops/{uid}/{type}.png
 * (generated by crop_buildings.py).
 *
 * GET /api/building-crop/[tileId]/[uid]/[type]
 *   tileId is accepted but unused — the output folder is keyed by uid only.
 *   type = "pre" | "post"
 */

import { NextRequest, NextResponse } from "next/server";
import fs from "fs";
import path from "path";

const CROPS_DIR = path.join(process.cwd(), "..", "output", "crops");

type Params = { tileId: string; uid: string; type: string };

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<Params> },
) {
  const { uid, type } = await params;

  if (type !== "pre" && type !== "post") {
    return new NextResponse("Invalid type", { status: 400 });
  }

  const filePath = path.join(CROPS_DIR, uid, `${type}.png`);

  if (!fs.existsSync(filePath)) {
    return new NextResponse("Not found", { status: 404 });
  }

  const buffer = fs.readFileSync(filePath);

  return new NextResponse(buffer, {
    status: 200,
    headers: {
      "Content-Type": "image/png",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
